name: eclipse-papyrus-snapcraft
license: GPL-3.0
summary: Logisim is a digital circuit simulator
description: |
  Github (compilation) : https://github.com/anrouxel/logisim-evolution-snapcraft
base: core18
grade: stable
confinement: strict

adopt-info: eclipse-papyrus-snapcraft

architectures:
  - build-on: amd64

apps:
  eclipse-papyrus-snapcraft:
    extensions: [gnome-3-28]
    command: bin/java -jar $SNAP/jar/Logisim-jar-with-dependencies.jar
    plugs:
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  eclipse-papyrus-snapcraft:
    plugin: maven
    source: https://git.eclipse.org/r/papyrus/org.eclipse.papyrus.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout 5.2.0 -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    build-packages:
      - git
      - sed
      - tree
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jre
