name: eclipse-papyrus-snapcraft
license: GPL-3.0
summary: Logisim is a digital circuit simulator
description: |
  Github (compilation) : https://github.com/anrouxel/logisim-evolution-snapcraft
base: core18
grade: stable
confinement: strict

adopt-info: eclipse-papyrus-snapcraft

architectures:
  - build-on: amd64

apps:
  eclipse-papyrus-snapcraft:
    extensions: [gnome-3-28]
    command: Papyrus/papyrus
    plugs:
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  eclipse-papyrus-snapcraft:
    plugin: maven
    source: https://git.eclipse.org/r/papyrus/org.eclipse.papyrus.git
    source-type: git
    maven-options:
      [-Dpapyrus.repo.main=https://download.eclipse.org/modeling/mdt/papyrus/updates/releases/2021-09/5.2.0/main/]
    maven-openjdk-version: '11'
    override-pull: |
      snapcraftctl pull
      git checkout 5.2.0 -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    build-packages:
      - git
      - sed
      - maven
    stage-packages:
      - libffi7
      - libfreetype6
      - libpng16-16
      - libgdk-pixbuf2.0-0
      - libsecret-1-0
      - libasound2
      - libxi6
      - libxrender1
      - libxtst6
